### ISSUE TITLE
Unable to install any custom rom on realme 1 CPH1859 model

### ISSUE THREAD

**Issue by AvAkanksh** [CPH1859/android_device_oppo_CPH1859#14]
I am trying to install lineageOs on my realme 1 device. I have seen many videos to install it, all of them are recommending to use deep testing to unlock the bootloader and then enter into fastboot method and install the lineageOs.

But the when i am using the deep testing apk to ask for approval, i.e when i submit the application it says that it failed to submit the application. Can anyone help me with this.

**Comment by blacklytning** [comment]
Join Telegram grp @Realme1Community
